## Deliverable 3. Create a Travel Itinerary Map.

In [3]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [71]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../VacationSearch/WeatherPy_vacation.csv")
vacation_df_BR = vacation_df.loc[(vacation_df["Country"] == "US")]
vacation_df_BR

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
5,14,Kapaa,US,72.12,broken clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
10,26,Redlands,US,79.68,haze,34.0556,-117.1825,Dynasty Suites Redlands
35,116,Hilo,US,76.28,mist,19.7297,-155.0900,Hilo Hawaiian Hotel
48,153,Morgan City,US,75.99,clear sky,29.6994,-91.2068,Hampton Inn & Suites Morgan City
61,185,Brownwood,US,75.20,scattered clouds,31.7093,-98.9912,La Quinta Inn & Suites by Wyndham Brownwood
75,241,San Patricio,US,84.61,broken clouds,28.0170,-97.5169,"Motel 6 Sinton, TX"
99,305,Saint George,US,72.07,clear sky,37.1041,-113.5841,Best Western Plus Abbey Inn
107,330,Makakilo City,US,73.29,light rain,21.3469,-158.0858,Marriott's Ko Olina Beach Club
133,393,Princeton,US,77.02,scattered clouds,25.5384,-80.4089,American Best Inn
148,432,Killeen,US,76.44,few clouds,31.1171,-97.7278,OYO Hotel Killeen
155,449,Corsicana,US,76.24,overcast clouds,32.0954,-96.4689,"Holiday Inn Express & Suites Corsicana I-45, a..."
201,556,Ewa Beach,US,74.70,light rain,21.3156,-158.0072,Uncle Junior Robert
216,605,Winston,US,73.40,clear sky,28.0317,-82.0148,Hampton Inn & Suites Lakeland-South Polk Parkway
232,647,Avera,US,70.48,overcast clouds,33.1940,-82.5271,NaN
241,674,Port Hueneme,US,74.88,broken clouds,34.1478,-119.1951,Hampton Inn Channel Islands Harbor
245,682,Kahului,US,78.82,scattered clouds,20.8947,-156.4700,Maui Seaside Hotel

In [44]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt><b>City</b></dt><dd>{City}</dd>
<dt><b>Country</b></dt><dd>{Country}</dd>
<dt><b>Current Weather</b></dt><dd>{Current Description}</dd>
<dt><b>Max Temp</b></dt><dd>{Max Temp} °F </dd>
</dl>
"""

# 3a. Get the data from each row and add it to========= the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,1,Vaini,TO,84.36,light rain,-21.2000,-175.2000,Keleti Beach Resort
1,4,Rikitea,PF,76.06,scattered clouds,-23.1203,-134.9692,People ThankYou
2,9,Pala,TD,78.04,overcast clouds,9.3642,14.9046,Nectar Hôtel de Pala
3,11,Saint-Philippe,RE,76.55,scattered clouds,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""
4,13,Georgetown,MY,78.89,few clouds,5.4112,100.3354,Cititel Penang
...,...,...,...,...,...,...,...,...
249,693,Bandarbeyla,SO,74.79,scattered clouds,9.4942,50.8122,JABIR HOTEL
250,694,Loreto,MX,72.03,few clouds,22.2667,-101.9667,José de Jesús Velásquez mora
251,696,Chimore,BO,77.09,overcast clouds,-16.9833,-65.1333,Bichito
252,698,Ojinaga,MX,80.56,clear sky,29.5667,-104.4167,Suites Las Palmas
253,702,Mayor Pablo Lagerenza,PY,81.01,overcast clouds,-19.9309,-60.7718,NaN

In [6]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [72]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df["City"]) == "Killeen"]
vacation_end = vacation_df.loc[(vacation_df["City"]) == "Killeen"]
vacation_stop1 = vacation_df.loc[(vacation_df["City"]) == "Winston"]
vacation_stop2 = vacation_df.loc[(vacation_df["City"]) == "Princeton"]
vacation_stop3 = vacation_df.loc[(vacation_df["City"]) == "Brownwood"]

In [73]:
start = (vacation_start.to_numpy()[0][5],vacation_start.to_numpy()[0][6]) 
end = (vacation_end.to_numpy()[0][5],vacation_end.to_numpy()[0][6]) 
stop1 = (vacation_stop1.to_numpy()[0][5],vacation_stop1.to_numpy()[0][6]) 
stop2 = (vacation_stop2.to_numpy()[0][5],vacation_stop2.to_numpy()[0][6]) 
stop3 = (vacation_stop3.to_numpy()[0][5],vacation_stop3.to_numpy()[0][6])

In [74]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or 
fig = gmaps.figure(center=(-18, -25), zoom_level=3.0)

route = gmaps.directions_layer(start,end,waypoints=[stop1,stop2,stop3],travel_mode = "DRIVING")

fig.add_layer(route)

fig

Figure(layout=FigureLayout(height='420px'))

In [75]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_stop1,vacation_stop2,vacation_stop3],ignore_index=True)

In [76]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt><b>City</b></dt><dd>{City}</dd>
<dt><b>Country</b></dt><dd>{Country}</dd>
<dt><b>Current Conditions</b></dt><dd>{Current Description}</dd>
<dt><b>Max Temp</b></dt><dd>{Max Temp} °F </dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [77]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))